### ISSUE TITLE
Plugin building/installation

### ISSUE THREAD

**Issue by dominikdomanski** [derrickgw/xilinx-reports-plugin#4]
Hi  Derrick,

As I'm checking different options for using Jenkins in FPGA development, I have encountered your repo. I'm  a newbie in Jenkins and I wonder how this plugin is installed in Jenkins?

Best regards,
Dominik

**Comment by lukipedio** [comment]
First download HPI file from release link :
https://github.com/derrickgw/xilinx-reports-plugin/releases/tag/release%2Fv0.6

Jenkins->Plugin Manager->Advanced->Upload Plugin (via *.hpi file)

**Comment by dominikdomanski** [comment]
Great! Thanks :)
